swagger: '2.0'
info:
  title: speech-api speech-to-text
  description: Speech API on API Gateway with a Cloud Run backend
  version: 1.0.1
schemes:
  - https
produces:
  - application/json
x-google-backend:
  address: https://speech-api-5ledmsck3a-ew.a.run.app
#  jwt_audience: https://speech-api-5ledmsck3a-ew.a.run.app
security:
  - google_id_token: []
paths:
    /hello:
      get:
        summary: Cloud Run hello world
        operationId: hello
        responses:
          '200':
            description: A successful response
            schema:
              type: string
    /v1/speech:
      post:
        summary: Convert speech snippet to text
        operationId: convertSpeech
        consumes:
          - "multipart/form-data"
# Not supported by GCP?
#        parameters:
#          - in: formData
#            name: speech_file
#            type: file
#            description: The speech snippet to convert.
        responses:
          "200":
            description: "successful operation"
            schema:
              $ref: "#/definitions/Transcript"
          "400":
            description: "Invalid snippet"
securityDefinitions:
  google_id_token:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "sa-speech-api-dev@geometric-ocean-284614.iam.gserviceaccount.com"
    x-google-jwks_uri: "https://www.googleapis.com/robot/v1/metadata/x509/sa-speech-api-dev@geometric-ocean-284614.iam.gserviceaccount.com"
    x-google-audiences: "https://speech-api-5ledmsck3a-ew.a.run.app"
definitions:
  Transcript:
    type: "object"
    properties:
      transcripts:
        type: "array"
        items:
          type: "string"